@startuml

class ManagedChannelBuilder {

+ static ManagedChannelBuilder<?> forAddress(String name, int port)
+ static ManagedChannelBuilder<?> forTarget(String target)
+ T directExecutor()
+ T executor(Executor executor)
+ T intercept(List<ClientInterceptor> interceptors)
+ T userAgent(String userAgent)
+ T overrideAuthority(String authority)
+ T usePlaintext(boolean skipNegotiation)
+ T nameResolverFactory(NameResolver.Factory resolverFactory)
+ T loadBalancerFactory(LoadBalancer.Factory loadBalancerFactory)
+ T decompressorRegistry(DecompressorRegistry registry)
+ T idleTimeout(long value, TimeUnit unit)

+ ManagedChannel build()
}

class AbstractManagedChannelImplBuilder {
# Attributes getNameResolverParams()
# abstract ClientTransportFactory buildTransportFactory();
}

class NettyChannelBuilder {
}

class OkHttpChannelBuilder {
}

class InProcessChannelBuilder {
}

ManagedChannelBuilder <-- AbstractManagedChannelImplBuilder
AbstractManagedChannelImplBuilder <-- NettyChannelBuilder
AbstractManagedChannelImplBuilder <-- OkHttpChannelBuilder
AbstractManagedChannelImplBuilder <-- InProcessChannelBuilder

@enduml
